"""call_script na analise

Revision ID: 38b50fc6219f
Revises: 93792a6d7cad
Create Date: 2026-09-01 16:01:15.898468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b50fc6219f'
down_revision: Union[str, Sequence[str], None] = '93792a6d7cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('call_script', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'call_script')
    # ### end Alembic commands ###
