"""produtos da empresa e canal do lead

Revision ID: 93792a6d7cad
Revises: fc2859a88803
Create Date: 2026-09-01 15:57:37.278873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93792a6d7cad'
down_revision: Union[str, Sequence[str], None] = 'fc2859a88803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


lead_channel = postgresql.ENUM('manual', 'whatsapp', 'landing_page', name='lead_channel')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    lead_channel.create(op.get_bind(), checkfirst=True)
    op.add_column('companies', sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('leads', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('channel', lead_channel, server_default='manual', nullable=False))
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('leads', 'channel')
    op.drop_column('leads', 'phone')
    op.drop_column('companies', 'products')
    lead_channel.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
