"""historico de mensagens e telegram_chat_id

Revision ID: bc943e4d9e10
Revises: 38b50fc6219f
Create Date: 2026-09-01 17:48:43.289279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc943e4d9e10'
down_revision: Union[str, Sequence[str], None] = '38b50fc6219f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Renomear o valor do enum 'whatsapp' -> 'telegram': o ciclo anterior implementou um
    # WhatsApp simulado antes da decisao de trocar por Telegram (ver TASKS.md Fase 1).
    # Linhas existentes com channel='whatsapp' viram 'telegram' automaticamente.
    op.execute("ALTER TYPE lead_channel RENAME VALUE 'whatsapp' TO 'telegram'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_message_id')
    )
    op.add_column('leads', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'telegram_chat_id')
    op.drop_table('lead_messages')
    # ### end Alembic commands ###

    op.execute("ALTER TYPE lead_channel RENAME VALUE 'telegram' TO 'whatsapp'")
